"use client";
import BlurredCard from "@/components/cards/BlurredCard";
import TextAnimation from "@/components/ui/textAnimation";
import { cn } from "@/lib/utils";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";
import { useEffect, useRef } from "react";

gsap.registerPlugin(ScrollTrigger);

const data = [
  {
    id: 1,
    amount: 3.8,
    unit: "%",
    currency: "",
    title: "average conversion rate",
    seoContext: "Performance metric for DTC fashion and beauty brands working with MOTIF®",
    ariaLabel: "Average conversion rate — 3.8%. Performance metric for DTC fashion and beauty brands working with MOTIF®",
  },
  {
    id: 2,
    amount: 93,
    unit: "+",
    currency: "",
    title: "brands helped",
    seoContext: "Fashion, luxury lifestyle, and beauty brands grown through MOTIF® incubation and partnership",
    ariaLabel: "Brands helped — over 93. Fashion, luxury lifestyle, and beauty brands grown through MOTIF® incubation and partnership",
  },
  {
    id: 3,
    amount: 1.537,
    unit: "B+",
    currency: "$",
    title: "total partner gmv",
    seoContext: "Total gross merchandise volume generated by MOTIF® partner brands globally",
    ariaLabel: "Total partner GMV — $1.537B+. Total gross merchandise volume generated by MOTIF® partner brands globally",
  },
  {
    id: 4,
    amount: 93,
    unit: "%",
    currency: "",
    title: "average growth",
    seoContext: "Average post-engagement growth rate for brands working with MOTIF® as a strategic partner",
    ariaLabel: "Average growth — 93%. Average post-engagement growth rate for brands working with MOTIF® as a strategic partner",
  },
];

const Driving = () => {
  const cardContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const ctx = gsap.context(() => {
      const cards = gsap.utils.toArray(".card") as HTMLElement[];

      if (!cards.length) return;

      const timeline = gsap.timeline({
        scrollTrigger: {
          trigger: cardContainerRef.current,
          start: "top center",
          end: () => `+=${cards.length * 300}`,
          scrub: 0.6,
        },
      });

      cards.forEach((card, idx) => {
        const xFrom = idx % 2 === 0 ? "-20%" : "20%";
        const rotFrom = idx % 2 === 0 ? -15 : 15;

        timeline.from(
          card,
          {
            opacity: 0,
            y: 80,
            x: xFrom,
            rotation: rotFrom,
            duration: 1.1,
            ease: "power3.out",
          },
          idx === cards.length - 1 ? idx * 0.3 + 0.1 : idx * 0.3
        );
      });
    }, cardContainerRef);

    return () => ctx.revert();
  }, []);

  return (
    <section
      ref={cardContainerRef}
      className="layout_normal w-full overflow-hidden"
      aria-label="MOTIF® growth performance metrics for fashion, beauty, and lifestyle brands"
    >
      <h2 className="sr-only">
        Results that reflect growth — how MOTIF® drives performance across conversions, retention, and revenue
      </h2>
      <p className="sr-only">
        MOTIF® helps fashion, beauty, and luxury lifestyle brands grow through strategic partnerships, resulting in higher conversion rates, strong average growth, and over $1.5B in total partner GMV. These results showcase the effectiveness of our incubator and growth partner model.
      </p>

      <div className="mt-40 mx-auto md:mt-60 w-[90%] md:w-[90%] lg:w-[70%]">
        <div className="mt-28 text-typo-primary">
          <div className="w-full md:w-[60%] lg:w-[50%] xl:w-[40%]">
            <h2 className="capitalize text-section_heading_sm md:text-section_heading_md lg:text-section_heading_lg 2xl:text-section_heading_2xl 3xl:text-[clamp(50px,2.5vw,60px)] font-semibold font-clash leading-[1.2em] ">
              <TextAnimation
                type="fadeUp"
                splitType="lines, words"
                animationOn="words"
                linesClass="overflow-hidden"
                stagger={0}
                duration={1.5}
              >
                Driving growth <br />
                through ambition <br />
                and dedication
              </TextAnimation>
            </h2>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-y-[20px] md:gap-y-0 gap-x-[20px] text-typo-primary mt-20">
          {data.map((el, idx) => (
            <div className={`card stat-${idx + 1} stat-anims`} key={el.id}>
              <BlurredCard
                className={cn(" aspect-[660/309]", {
                  "md:mb-6": idx % 2 === 0,
                  "md:mt-[-20px]": idx > 1,
                  "md:mt-[2.5rem]": idx === 1,
                  "md:mt-[1.2rem]": idx === 3,
                })}
              >
                <article
                  className={cn(
                    "flex flex-col justify-center p-10 w-full h-full Xpy-10 Xmd:py-28 rounded-2xl",
                    {}
                  )}
                >
                  <div>
                    <span className="text-[calc(100vw/8)] md:text-[5.3vw] 3xl:text-[clamp(100px,5.vw,110px)] font-medium font-clash leading-none">
                      {el.currency}
                      <span className="ammount">{el.amount}</span>
                      {el.unit}
                    </span>
                    {/* 🔒 SEO/Accessibility Only */}
                   <span className="sr-only">{el.ariaLabel}</span>
                  </div>
                  <h3 className="mt-3 font-helvetica text-[calc(100vw/32)] md:text-[1.2vw] font-semibold uppercase">
                    {el.title}
                  </h3>
                  {/* 🔒 SEO/Accessibility Only */}
                   <span className="sr-only">{el.seoContext}</span>
                </article>
              </BlurredCard>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Driving;
